ci:
  collect:
    numberOfRuns: 1

  assert:
    preset: lighthouse:no-pwa
    assertions:
      color-contrast: warn
      canonical: off
      csp-xss: off

  upload:
    target: temporary-public-storage
