ci:
  collect:
    numberOfRuns: 1

  assert:
    preset: lighthouse:no-pwa
    assertions:
      color-contrast: warn
      canonical: off
      csp-xss: off
      # TODO remove this when this PR is merged: https://github.com/JulianCataldo/web-garden/pull/72
      crawlable-anchors: off

  upload:
    target: temporary-public-storage
