ci:
  collect:
    numberOfRuns: 1
    staticDistDir: dist

  assert:
    preset: lighthouse:no-pwa
    assertions:
      color-contrast: warn
      canonical: off
      csp-xss: off
      # Lints we can't fix in blog pages. Make sure these don't propagate to
      # other pages!
      offscreen-images: warn
      errors-in-console: warn
      unsized-images: warn

  upload:
    target: temporary-public-storage
