name: CI & CD

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  ci:
    name: CI

    runs-on: ubuntu-24.04
    timeout-minutes: 10

    # Only run if this is not a pull request, or for pull requests on forks
    if: github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name != 'AlexTMjugador/Home'

    steps:
      - name: 📥 Checkout source
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version-file: .nvmrc

      - name: 📥 Install dependencies
        run: npm ci

      - name: "🔍 Static analysis: run Prettier"
        run: npm run format

      - name: "🔍 Static analysis: run ESLint"
        run: npm run lint

      - name: 🔨 Build website
        run: npm run build

      - name: 📤 Upload website distribution bundle
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: Web distribution bundle
          path: dist

      - name: "🔍 Run Lighthouse CI"
        uses: treosh/lighthouse-ci-action@fcd65974f7c4c2bf0ee9d09b84d2489183c29726 # v12
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        with:
          temporaryPublicStorage: true

  cd:
    name: CD

    runs-on: ubuntu-24.04
    timeout-minutes: 10

    needs: ci

    permissions:
      deployments: write

    steps:
      - name: 📥 Download website distribution bundle
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
        with:
          name: Web distribution bundle
          path: dist

      - name: 📤 Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca # v1
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: home
          branch: ${{ github.ref_name }}
          directory: dist
